CONTIKI_PROJECT = elfloader-test

all: $(CONTIKI_PROJECT).axf
	@echo " "
	@echo "******************** Build done ********************"
	@echo " "


CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
